### ISSUE TITLE
執行問題

### ISSUE THREAD

**Issue by yuyu0520** [Luckylau/python-web-frame#1]
你好~正在學習pecan框架，想利用你的code來做範本練習，請問一下執行指令是pecan serve config.py嗎?執行時有碰到以下錯誤代碼:
Traceback (most recent call last):
  File "/home/may/venv/lib/python3.8/site-packages/pecan/configuration.py", line 110, in __getattr__
    return self.__values__[name]
KeyError: 'server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/may/venv/bin/pecan", line 11, in <module>
    load_entry_point('pecan', 'console_scripts', 'pecan')()
  File "/home/may/venv/lib/python3.8/site-packages/pecan/commands/base.py", line 97, in handle_command_line
    runner.run(sys.argv[1:])
  File "/home/may/venv/lib/python3.8/site-packages/pecan/commands/base.py", line 92, in run
    self.commands[ns.command_name]().run(ns)
  File "/home/may/venv/lib/python3.8/site-packages/pecan/commands/serve.py", line 39, in run
    self.serve(app, app.config)
  File "/home/may/venv/lib/python3.8/site-packages/pecan/commands/serve.py", line 152, in serve
    self._serve(app, conf)
  File "/home/may/venv/lib/python3.8/site-packages/pecan/commands/serve.py", line 115, in _serve
    host, port = conf.server.host, int(conf.server.port)
  File "/home/may/venv/lib/python3.8/site-packages/pecan/configuration.py", line 113, in __getattr__
    raise AttributeError(msg)
AttributeError: 'pecan.conf' object has no attribute 'server'

**Comment by yuyu0520** [comment]
試著用cmd/api.py執行，也會有以下問題:
python api.py
Traceback (most recent call last):
  File "api.py", line 13, in <module>
    main()
  File "api.py", line 8, in main
    application = app.setup_app()
TypeError: setup_app() missing 1 required positional argument: 'config'

查看setup_app() func並不需要帶任何參數，請問是我有缺少什麼參數嗎?
